name:                juniper
version:             0.1.1
github:              "seanhess/juniper"
license:             BSD3
author:              "Sean Hess"
maintainer:          "seanhess@gmail.com"
copyright:           "All Rights Reserved"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seanhess/juniper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64
- bytestring
- containers
- data-default
- file-embed
- http-types
- lens
- lucid
- mtl
- raw-strings-qq
- scotty
- stm
- string-conversions
- text
- time
- unordered-containers
- vector
- wai
- wai-middleware-static

library:
  source-dirs: src

executables:
  juniper-exe:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wname-shadowing
    - -Wincomplete-patterns
    # - -Wall
    dependencies:
    - record-dot-preprocessor
    - record-hasfield
    - juniper

tests:
  juniper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - juniper
